---
name: Generate Amplify Ruleset

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: github.repository == 'amplify-security/opengrep-rules'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: '3.13'
      - run: pip3 install pyyaml
      - name: generate Amplify rule set
        run: python3 scripts/generate-amplify-ruleset.py
      - name: update latest release
        # yes, this action is no longer maintained.
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          files: |
            rules.json
